// Categorias e Subcategorias Padrão - Meu Financeiro IA

export const DEFAULT_EXPENSE_CATEGORIES = [
  {
    id: 'cat_moradia',
    name: 'Moradia',
    icon: 'home',
    color: '#3B82F6',
    subcategories: [
      { id: 'sub_aluguel', name: 'Aluguel' },
      { id: 'sub_condominio', name: 'Condomínio' },
      { id: 'sub_energia', name: 'Energia Elétrica' },
      { id: 'sub_agua', name: 'Água e Esgoto' },
      { id: 'sub_gas', name: 'Gás' },
      { id: 'sub_internet', name: 'Internet / TV' },
      { id: 'sub_manutencao_casa', name: 'Manutenção / Reforma' },
      { id: 'sub_iptu', name: 'IPTU' },
    ],
  },
  {
    id: 'cat_alimentacao',
    name: 'Alimentação',
    icon: 'utensils',
    color: '#10B981',
    subcategories: [
      { id: 'sub_mercado', name: 'Mercado / Supermercado' },
      { id: 'sub_restaurante', name: 'Restaurante' },
      { id: 'sub_delivery', name: 'Delivery / iFood' },
      { id: 'sub_padaria', name: 'Padaria' },
      { id: 'sub_lanches', name: 'Lanches e Cafés' },
    ],
  },
  {
    id: 'cat_transporte',
    name: 'Transporte',
    icon: 'car',
    color: '#F59E0B',
    subcategories: [
      { id: 'sub_combustivel', name: 'Combustível' },
      { id: 'sub_uber', name: 'Uber / 99 / Táxi' },
      { id: 'sub_transporte_pub', name: 'Transporte Público' },
      { id: 'sub_estacionamento', name: 'Estacionamento / Pedágio' },
      { id: 'sub_manutencao_auto', name: 'Manutenção Veículo' },
      { id: 'sub_seguro_auto', name: 'Seguro Veículo' },
      { id: 'sub_ipva', name: 'IPVA / Licenciamento' },
    ],
  },
  {
    id: 'cat_saude',
    name: 'Saúde',
    icon: 'heart-pulse',
    color: '#EC4899',
    subcategories: [
      { id: 'sub_farmacia', name: 'Farmácia / Medicamentos' },
      { id: 'sub_consultas', name: 'Médicos e Consultas' },
      { id: 'sub_dentista', name: 'Dentista' },
      { id: 'sub_terapia', name: 'Terapia / Psicologia' },
      { id: 'sub_plano_saude', name: 'Plano de Saúde' },
      { id: 'sub_exames', name: 'Exames e Laboratório' },
    ],
  },
  {
    id: 'cat_lazer',
    name: 'Lazer & Entretenimento',
    icon: 'party-popper',
    color: '#8B5CF6',
    subcategories: [
      { id: 'sub_cinema', name: 'Cinema / Shows' },
      { id: 'sub_bares', name: 'Bares e Festas' },
      { id: 'sub_viagens', name: 'Viagens e Hospedagem' },
      { id: 'sub_passeios', name: 'Passeios' },
      { id: 'sub_jogos', name: 'Jogos e Hobbies' },
    ],
  },
  {
    id: 'cat_assinaturas',
    name: 'Assinaturas & Serviços',
    icon: 'repeat',
    color: '#06B6D4',
    subcategories: [
      { id: 'sub_streaming', name: 'Streaming (Netflix/Spotify/Prime)' },
      { id: 'sub_apps', name: 'Aplicativos e Softwares' },
      { id: 'sub_academia', name: 'Academia / Fitness' },
      { id: 'sub_clube', name: 'Clubes de Assinatura' },
    ],
  },
  {
    id: 'cat_educacao',
    name: 'Educação',
    icon: 'graduation-cap',
    color: '#6366F1',
    subcategories: [
      { id: 'sub_cursos', name: 'Cursos e Treinamentos' },
      { id: 'sub_faculdade', name: 'Faculdade / Escola' },
      { id: 'sub_livros', name: 'Livros e Material' },
      { id: 'sub_idiomas', name: 'Idiomas' },
    ],
  },
  {
    id: 'cat_compras',
    name: 'Compras Pessoais',
    icon: 'shopping-bag',
    color: '#14B8A6',
    subcategories: [
      { id: 'sub_roupas', name: 'Roupas e Calçados' },
      { id: 'sub_eletronicos', name: 'Eletrônicos e Gadgets' },
      { id: 'sub_beleza', name: 'Cuidados Pessoais / Cosméticos' },
      { id: 'sub_presentes', name: 'Presentes' },
    ],
  },
  {
    id: 'cat_dividas',
    name: 'Dívidas & Empréstimos',
    icon: 'badge-percent',
    color: '#EF4444',
    subcategories: [
      { id: 'sub_parcela_emprestimo', name: 'Parcela de Empréstimo' },
      { id: 'sub_parcela_financiamento', name: 'Financiamento' },
      { id: 'sub_juros_cartao', name: 'Juros de Cartão / Cheque Especial' },
    ],
  },
  {
    id: 'cat_investimentos',
    name: 'Investimentos & Aportes',
    icon: 'trending-up',
    color: '#10B981',
    subcategories: [
      { id: 'sub_reserva', name: 'Reserva de Emergência' },
      { id: 'sub_renda_fixa', name: 'Renda Fixa / CDB / Tesouro' },
      { id: 'sub_renda_variavel', name: 'Ações / FIIs / Cripto' },
      { id: 'sub_previdencia', name: 'Previdência Privada' },
    ],
  },
  {
    id: 'cat_outros_gastos',
    name: 'Outros Gastos',
    icon: 'more-horizontal',
    color: '#9CA3AF',
    subcategories: [
      { id: 'sub_imprevistos', name: 'Imprevistos' },
      { id: 'sub_taxas', name: 'Taxas Bancárias' },
      { id: 'sub_doacoes', name: 'Doações' },
      { id: 'sub_diversos', name: 'Diversos' },
    ],
  },
];

export const DEFAULT_INCOME_CATEGORIES = [
  {
    id: 'cat_salario',
    name: 'Salário & Remuneração',
    icon: 'briefcase',
    color: '#10B981',
    subcategories: [
      { id: 'sub_salario_fixo', name: 'Salário Fixo' },
      { id: 'sub_decimo_terceiro', name: '13º Salário' },
      { id: 'sub_ferias', name: 'Férias' },
      { id: 'sub_bonus', name: 'Bônus / PLR' },
    ],
  },
  {
    id: 'cat_renda_extra',
    name: 'Renda Extra & Freelance',
    icon: 'sparkles',
    color: '#3B82F6',
    subcategories: [
      { id: 'sub_freelance', name: 'Freelancer / Serviços' },
      { id: 'sub_vendas', name: 'Venda de Produtos / Desapego' },
      { id: 'sub_aulas', name: 'Consultorias / Aulas' },
    ],
  },
  {
    id: 'cat_rendimentos',
    name: 'Rendimentos & Dividendos',
    icon: 'coins',
    color: '#F59E0B',
    subcategories: [
      { id: 'sub_dividendos', name: 'Dividendos / JCP' },
      { id: 'sub_rendimento_aplicacao', name: 'Rendimento de Aplicações' },
      { id: 'sub_aluguel_recebido', name: 'Aluguel Recebido' },
    ],
  },
  {
    id: 'cat_outras_receitas',
    name: 'Outras Receitas',
    icon: 'arrow-down-left',
    color: '#8B5CF6',
    subcategories: [
      { id: 'sub_reembolso', name: 'Reembolsos' },
      { id: 'sub_presente_dinheiro', name: 'Presentes em Dinheiro' },
      { id: 'sub_outros_ganhos', name: 'Outros Ganhos' },
    ],
  },
];
